deposit_path: /Users/jyesselm/gdrive/sequences_and_oligos
primer_gsheet_url: https://docs.google.com/spreadsheets/d/1_oGLJRZMG8zNoc6yF5lJV7k0MVP6XgVD9A2ya0XPAXQ/gviz/tq?tqx=out:csv&sheet=oligos
sequence_gsheet_url: https://docs.google.com/spreadsheets/d/1ihU99DtK10J9yPDLiSQ9KdEC7KaddIn7Ta3tb_HFz8U/gviz/tq?tqx=out:csv&sheet=all
